apiVersion: v1
kind: Service
metadata:
  name: expressapp
spec:
  selector:
    app: expressapp
  type: ClusterIP
  ports:
  - name: expressapp
    protocol: TCP
    port: 5000
    targetPort: 5000
