apiVersion: apps/v1
kind: Deployment
metadata:
  name: expressapp
  labels:
    app: expressapp
spec:
  selector:
    matchLabels:
      app: expressapp
  replicas: 2
  template:
    metadata:
      labels:
        app: expressapp
    spec:
      containers:
      - name: expressapp
        image: tijani119/my-express-app:latest
        ports:
        - containerPort: 5000











